version: '3.8'
services:
  backend:
    build: ./resumeanalyzer
    container_name: resumeanalyzer-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
    depends_on:
      - db
  frontend:
    build: ./resumeanalyzer-ui
    container_name: resumeanalyzer-frontend
    ports:
      - "3000:80"
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
    depends_on:
      - backend
  db:
    image: postgres:15-alpine
    container_name: resumeanalyzer-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  aiagent:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # persist downloaded models
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Optional: use GPU if supported
    environment:
      - OLLAMA_MODELS_PATH=/root/.ollama
volumes:
  pgdata:
